name: Docker Image CI

on:
  workflow_dispatch: # Use manual trigger for controlled runs

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@v5

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build Docker images
      env:
        IMAGE_NAME_BACKEND: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}_backend:${{ (github.ref_name == 'main') && 'latest' || 'stage' }}
      run: |
        docker build -f backend/Dockerfile --tag $IMAGE_NAME_BACKEND backend
        docker push $IMAGE_NAME_BACKEND

    - name: Invoke deployment
      if: ${{ env.WEBHOOK_URL != '' }}
      run: |
        curl -X POST "${{ secrets.WEBHOOK_URL }}" \
          -H "Content-Type: application/json" \
          -d '{"repository": "${{ github.repository }}", "ref": "${{ github.ref }}"}'
